spring:
  application:
    name: SMS

  datasource:
    url: jdbc:mysql://localhost:3306/sms
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  #
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        globally_quoted_identifiers: true

server:
  port: 9090

logging:
  level:
    root: info
    com.example.sms: debug
    org.hibernate.sql: info
    org.springframework: info

app:
  upload:
    dir=uploads/students: